name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy repository to test_halunka folder
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }} 
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            rm -rf /home/bohdan_halunka/test_halunka
            git clone https://github.com/ThisIsHalunka/test_cicd.git /home/bohdan_halunka/test_halunka
